fix(deps): require rust 1.70 as required by home v0.5.9
CI was failing: https://github.com/nextcloud/notify_push/actions/runs/7612045148/job/20728772460?pr=382

```
error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p home@0.5.9 --precise ver
where `ver` is the latest version of `home` supporting rustc 1.69.0
```